#!/bin/sh

SRC="compiler.c";
BIN_DIR="./target/bin";
BINARY="${BIN_DIR}/famc";
CC="${CC:-clang}"
CFLAGS="${CFLAGS:- -O3}"
CSTRICT="-nostdlib \
	-fvisibility=hidden \
	-std=c89 \
	-Wall \
	-Wextra \
	-Werror \
	-Wshadow \
	-Wdouble-promotion \
	-Wpointer-arith \
	-Wredundant-decls \
	-Wstrict-prototypes \
	-pedantic"

mkdir -p ${BIN_DIR};
COMMAND="${CC} ${CFLAGS} ${CSTRICT} ${SRC} -o ${BINARY}";
echo ${COMMAND};
${COMMAND} || exit 1;
