#!/bin/sh

if [ "$CI" = "true" ]; then
	sudo apt update
	sudo apt install tcc
fi

CC=tcc
SRC=famc.c
CFLAGS="-O3 \
	-nostdlib \
	-fno-builtin \
	-std=c89 \
	-Wall \
	-Wextra \
	-Werror \
	-Wshadow \
	-Wdouble-promotion \
	-Wpointer-arith \
	-Wredundant-decls \
	-Wstrict-prototypes";

COMMAND="${CC} ${CFLAGS} -o famc ${SRC}";
echo ${COMMAND};
${COMMAND} || exit 1;
